[package]
name = "tokio_timer"
version = "0.1.0"
edition = "2021"

[dependencies]
floem = {git = "https://github.com/lapce/floem", features=["futures"]}
tokio = { version = "1.40.0", features = ["time", "rt-multi-thread"] }
tokio-stream = "0.1.16"
